### PR TITLE
Fingerprint improvements OPS-543

### PR DESCRIPTION
**Pull request by crunis**
This should merge the fingerprint improvements into release

### CODE REVIEW

**Comment by crunis** [comment]
@stevecrozz and @tony-spataro-rs , this is my PR to merge my fingerprint changes from release_candidate to release. It is showing several commits from you that weren't in release. 
Is it not able to automatically merge. 
Any suggestions on how to proceed ? I feel like the safest thing to do would be to manually merge only my change, but should we do with all your commits that are in release_candidate but not release?

**Comment by stevecrozz** [comment]
I'd probably just force push whatever you want to release. We can see if tony cares about losing any of this stuff, but I do not.

**Comment by tony-spataro-rs** [comment]
I just merged RC into release (and vice-versa) on my local box and it merges cleanly (all conflicts were automatically resolved). GitHub does not resolve conflicts when you perform a Web-based merge -- they don't want to take responsibility. But the merge is clean if you do it from the CLI.

I propose that @crunis just merges release_candidate into release.

I also propose that we switch the branch-naming scheme for errbit so it aligns with the new names we use elsewhere: production, staging. But I'll leave that up to @enrikitus and @crunis .

**Comment by crunis** [comment]
You were right, in the CLI it merges without complains. Done !

**Pull request merged**
